name: CI
on: [ push ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4

      - uses: moneymeets/action-setup-python-poetry@master

      - uses: moneymeets/moneymeets-composite-actions/lint-python@master

      - run: poetry run pytest --cov --cov-fail-under=50
        env:
          DJANGO_DEBUG: 1

  build-image:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - uses: moneymeets/moneymeets-composite-actions/detect-python-version@master
        id: 'detect-versions'

      - name: Build image
        run: |
          docker build \
            --build-arg PYTHON_VERSION_CONSTRAINT="${{ steps.detect-versions.outputs.python-version-constraint }}" \
            --build-arg POETRY_VERSION="${{ steps.detect-versions.outputs.poetry-version }}" \
            -t sepacetamol-ci .
#          TODO: share image tag when pushing part is implemented
