name: CI
on: [push]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    container: moneymeets/ruby-python-awscli:python3.8-poetry1.0-github

    steps:
      - uses: actions/checkout@v1

      - name: Restore virtualenv from Poetry cache
        uses: actions/cache@v1
        id: poetry-cache
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: poetry-${{ hashFiles('**/poetry.lock') }}

      - name: Create virtualenv and install dependencies
        if: steps.poetry-cache.outputs.cache-hit != 'true'
        run: poetry install

      - name: Run linter
        run: poetry run flake8
