# This file was added by Pulumi and should not be edited manually. To edit the contents of this file, please go
# to the github-management project in moneymeets-pulumi and call `pulumi up` after changing the template file.

name: Deploy
on: [ deployment ]
jobs:
  deploy-heroku:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      deployments: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          show-progress: false

      - uses: moneymeets/moneymeets-composite-actions/set-deployment-status@master
        with:
          environment: ${{ github.event.deployment.environment }}
          state: in_progress

      - uses: moneymeets/action-heroku-deploy@master
        with:
          HEROKU_APP: sepacetamol
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_TOKEN }}

      - uses: getsentry/action-release@v1
        env:
          SENTRY_ORG: moneymeets
          SENTRY_PROJECT: sepacetamol
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_MONEYMEETS_TOKEN }}
        with:
          environment: ${{ github.event.deployment.environment }}

      - uses: moneymeets/moneymeets-composite-actions/set-deployment-status@master
        if: always()
        with:
          environment: ${{ github.event.deployment.environment }}
          state: ${{ job.status == 'success' && 'success' || 'failure' }}
