# This file was added by Pulumi and should not be edited manually. To edit the contents of this file, please go
# to the github-management project in moneymeets-pulumi and call `pulumi up` after changing the template file.

name: Deploy
on:
  repository_dispatch:
    event_type: [ pulumi ]

jobs:
  deploy-ecs:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      deployments: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          show-progress: false

      - uses: moneymeets/action-ecs-deploy@master
        with:
          environment: ${{ github.event.client_payload.environment }}
          ecr_repository: ${{ vars.APPLICATION_ID }}
          deployment_tag: ${{ vars.DEPLOYMENT_BY_GITHUB_ACTION_TAG }}
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ vars.AWS_DEFAULT_REGION }}
